sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t docker-ubuntu .
      - docker images
      - docker tag docker-ubuntu luismcplopes/docker-ubuntu

    - stage: test
      script: docker run --rm luismcplopes/docker-ubuntu cat /etc/os-*release
      script: docker run --rm luismcplopes/docker-ubuntu cat /etc/apt/sources.list
